services:
  postgres:
    networks:
      - blog_network
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: to_do_list
      PGDATA: /data/postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: jlu6872@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - blog_network

networks:
  blog_network:

volumes:
  postgres:
  pgadmin: